import type { MrtLineCode } from "./mrt-colors";

export const MRT_LINE_SEQUENCES = {
  NSL: [
    [
      "JURONG EAST",
      "BUKIT BATOK",
      "BUKIT GOMBAK",
      "CHOA CHU KANG",
      "YEW TEE",
      "KRANJI",
      "MARSILING",
      "WOODLANDS",
      "ADMIRALTY",
      "SEMBAWANG",
      "CANBERRA",
      "YISHUN",
      "KHATIB",
      "YIO CHU KANG",
      "ANG MO KIO",
      "BISHAN",
      "BRADDELL",
      "TOA PAYOH",
      "NOVENA",
      "NEWTON",
      "ORCHARD",
      "SOMERSET",
      "DHOBY GHAUT",
      "CITY HALL",
      "RAFFLES PLACE",
      "MARINA BAY",
      "MARINA SOUTH PIER",
    ],
  ],
  EWL: [
    [
      "PASIR RIS",
      "TAMPINES",
      "SIMEI",
      "TANAH MERAH",
      "BEDOK",
      "KEMBANGAN",
      "EUNOS",
      "PAYA LEBAR",
      "ALJUNIED",
      "KALLANG",
      "LAVENDER",
      "BUGIS",
      "TANJONG PAGAR",
      "OUTRAM PARK",
      "TIONG BAHRU",
      "REDHILL",
      "QUEENSTOWN",
      "COMMONWEALTH",
      "BUONA VISTA",
      "DOVER",
      "CLEMENTI",
      "JURONG EAST",
      "CHINESE GARDEN",
      "LAKESIDE",
      "BOON LAY",
      "PIONEER",
      "JOO KOON",
      "GUL CIRCLE",
      "TUAS CRESCENT",
      "TUAS WEST ROAD",
      "TUAS LINK",
    ],
    ["TANAH MERAH", "EXPO", "CHANGI AIRPORT"],
  ],
  NEL: [
    [
      "HARBOURFRONT",
      "OUTRAM PARK",
      "CHINATOWN",
      "CLARKE QUAY",
      "DHOBY GHAUT",
      "LITTLE INDIA",
      "FARRER PARK",
      "BOON KENG",
      "POTONG PASIR",
      "WOODLEIGH",
      "SERANGOON",
      "KOVAN",
      "HOUGANG",
      "BUANGKOK",
      "SENGKANG",
      "PUNGGOL",
    ],
  ],
  CCL: [
    [
      "DHOBY GHAUT",
      "BRAS BASAH",
      "ESPLANADE",
      "PROMENADE",
      "NICOLL HIGHWAY",
      "STADIUM",
      "MOUNTBATTEN",
      "DAKOTA",
      "PAYA LEBAR",
      "MACPHERSON",
      "TAI SENG",
      "BARTLEY",
      "SERANGOON",
      "LORONG CHUAN",
      "BISHAN",
      "MARYMOUNT",
      "CALDECOTT",
      "BOTANIC GARDENS",
      "FARRER ROAD",
      "HOLLAND VILLAGE",
      "BUONA VISTA",
      "ONE-NORTH",
      "KENT RIDGE",
      "HAW PAR VILLA",
      "PASIR PANJANG",
      "LABRADOR PARK",
      "TELOK BLANGAH",
      "HARBOURFRONT",
    ],
    ["PROMENADE", "BAYFRONT", "MARINA BAY"],
  ],
  DTL: [
    [
      "BUKIT PANJANG",
      "CASHEW",
      "HILLVIEW",
      "BEAUTY WORLD",
      "KING ALBERT PARK",
      "SIXTH AVENUE",
      "TAN KAH KEE",
      "BOTANIC GARDENS",
      "STEVENS",
      "NEWTON",
      "LITTLE INDIA",
      "ROCHOR",
      "BUGIS",
      "PROMENADE",
      "BAYFRONT",
      "DOWNTOWN",
      "TELOK AYER",
      "CHINATOWN",
      "FORT CANNING",
      "BENCOOLEN",
      "JALAN BESAR",
      "BENDEMEER",
      "GEYLANG BAHRU",
      "MATTAR",
      "MACPHERSON",
      "UBI",
      "KAKI BUKIT",
      "BEDOK NORTH",
      "BEDOK RESERVOIR",
      "TAMPINES WEST",
      "TAMPINES",
      "TAMPINES EAST",
      "UPPER CHANGI",
      "EXPO",
    ],
  ],
  TEL: [
    [
      "WOODLANDS NORTH",
      "WOODLANDS",
      "WOODLANDS SOUTH",
      "SPRINGLEAF",
      "LENTOR",
      "MAYFLOWER",
      "BRIGHT HILL",
      "UPPER THOMSON",
      "CALDECOTT",
      "STEVENS",
      "NAPIER",
      "ORCHARD BOULEVARD",
      "ORCHARD",
      "GREAT WORLD",
      "HAVELOCK",
      "OUTRAM PARK",
      "MAXWELL",
      "SHENTON WAY",
      "MARINA BAY",
      "MARINA SOUTH",
      "GARDENS BY THE BAY",
      "TANJONG RHU",
      "KATONG PARK",
      "TANJONG KATONG",
      "MARINE PARADE",
      "MARINE TERRACE",
      "SIGLAP",
      "BAYSHORE",
      "SUNGEI BEDOK",
    ],
  ],
} as const satisfies Record<MrtLineCode, readonly (readonly string[])[]>;
