import { DEFAULT_STATION_COLOR, LRT_LINE_COLOR, MRT_LINE_COLORS } from "./mrt-colors";

export function getStationColor(stationName: string): string {
  const name = stationName.toUpperCase();
  if (name.match(/(JURONG EAST|BUKIT BATOK|BUKIT GOMBAK|CHOA CHU KANG|YEW TEE|KRANJI|MARSILING|WOODLANDS|ADMIRALTY|SEMBAWANG|CANBERRA|YISHUN|KHATIB|YIO CHU KANG|ANG MO KIO|BISHAN|BRADDELL|TOA PAYOH|NOVENA|NEWTON|ORCHARD|SOMERSET|DHOBY GHAUT|CITY HALL|RAFFLES PLACE|MARINA BAY|MARINA SOUTH PIER)/)) return MRT_LINE_COLORS.NSL; // NSL Red
  if (name.match(/(PASIR RIS|TAMPINES|SIMEI|TANAH MERAH|BEDOK|KEMBANGAN|EUNOS|PAYA LEBAR|ALJUNIED|KALLANG|LAVENDER|BUGIS|TANJONG PAGAR|OUTRAM PARK|TIONG BAHRU|REDHILL|QUEENSTOWN|COMMONWEALTH|BUONA VISTA|DOVER|CLEMENTI|CHINESE GARDEN|LAKESIDE|BOON LAY|PIONEER|JOO KOON|GUL CIRCLE|TUAS)/)) return MRT_LINE_COLORS.EWL; // EWL Green
  if (name.match(/(HARBOURFRONT|CHINATOWN|CLARKE QUAY|LITTLE INDIA|FARRER PARK|BOON KENG|POTONG PASIR|WOODLEIGH|SERANGOON|KOVAN|HOUGANG|BUANGKOK|SENGKANG|PUNGGOL)/)) return MRT_LINE_COLORS.NEL; // NEL Purple
  if (name.match(/(BRAS BASAH|ESPLANADE|PROMENADE|NICOLL HIGHWAY|STADIUM|MOUNTBATTEN|DAKOTA|MACPHERSON|TAI SENG|BARTLEY|LORONG CHUAN|MARYMOUNT|CALDECOTT|BOTANIC GARDENS|FARRER ROAD|HOLLAND VILLAGE|ONE-NORTH|KENT RIDGE|HAW PAR VILLA|PASIR PANJANG|LABRADOR PARK|TELOK BLANGAH|BAYFRONT)/)) return MRT_LINE_COLORS.CCL; // CCL Yellow
  if (name.match(/(BUKIT PANJANG|CASHEW|HILLVIEW|BEAUTY WORLD|KING ALBERT PARK|SIXTH AVENUE|TAN KAH KEE|STEVENS|ROCHOR|DOWNTOWN|TELOK AYER|FORT CANNING|BENCOOLEN|JALAN BESAR|BENDEMEER|GEYLANG BAHRU|MATTAR|UBI|KAKI BUKIT|BEDOK NORTH|BEDOK RESERVOIR|TAMPINES WEST|TAMPINES EAST|UPPER CHANGI|EXPO)/)) return MRT_LINE_COLORS.DTL; // DTL Blue
  if (name.match(/(WOODLANDS NORTH|WOODLANDS SOUTH|SPRINGLEAF|LENTOR|MAYFLOWER|BRIGHT HILL|UPPER THOMSON|NAPIER|ORCHARD BOULEVARD|GREAT WORLD|HAVELOCK|MAXWELL|SHENTON WAY|MARINA SOUTH|GARDENS BY THE BAY)/)) return MRT_LINE_COLORS.TEL; // TEL Brown
  if (name.match(/(LRT)/)) return LRT_LINE_COLOR; // LRT Grey

  return DEFAULT_STATION_COLOR; // Default Blue
}
