export function getStationColor(stationName: string): string {
  const name = stationName.toUpperCase();
  if (name.match(/(JURONG EAST|BUKIT BATOK|BUKIT GOMBAK|CHOA CHU KANG|YEW TEE|KRANJI|MARSILING|WOODLANDS|ADMIRALTY|SEMBAWANG|CANBERRA|YISHUN|KHATIB|YIO CHU KANG|ANG MO KIO|BISHAN|BRADDELL|TOA PAYOH|NOVENA|NEWTON|ORCHARD|SOMERSET|DHOBY GHAUT|CITY HALL|RAFFLES PLACE|MARINA BAY|MARINA SOUTH PIER)/)) return "#d11141"; // NSL Red
  if (name.match(/(PASIR RIS|TAMPINES|SIMEI|TANAH MERAH|BEDOK|KEMBANGAN|EUNOS|PAYA LEBAR|ALJUNIED|KALLANG|LAVENDER|BUGIS|TANJONG PAGAR|OUTRAM PARK|TIONG BAHRU|REDHILL|QUEENSTOWN|COMMONWEALTH|BUONA VISTA|DOVER|CLEMENTI|CHINESE GARDEN|LAKESIDE|BOON LAY|PIONEER|JOO KOON|GUL CIRCLE|TUAS)/)) return "#00a651"; // EWL Green
  if (name.match(/(HARBOURFRONT|CHINATOWN|CLARKE QUAY|LITTLE INDIA|FARRER PARK|BOON KENG|POTONG PASIR|WOODLEIGH|SERANGOON|KOVAN|HOUGANG|BUANGKOK|SENGKANG|PUNGGOL)/)) return "#9b26b6"; // NEL Purple
  if (name.match(/(BRAS BASAH|ESPLANADE|PROMENADE|NICOLL HIGHWAY|STADIUM|MOUNTBATTEN|DAKOTA|MACPHERSON|TAI SENG|BARTLEY|LORONG CHUAN|MARYMOUNT|CALDECOTT|BOTANIC GARDENS|FARRER ROAD|HOLLAND VILLAGE|ONE-NORTH|KENT RIDGE|HAW PAR VILLA|PASIR PANJANG|LABRADOR PARK|TELOK BLANGAH|BAYFRONT)/)) return "#fca311"; // CCL Yellow
  if (name.match(/(BUKIT PANJANG|CASHEW|HILLVIEW|BEAUTY WORLD|KING ALBERT PARK|SIXTH AVENUE|TAN KAH KEE|STEVENS|ROCHOR|DOWNTOWN|TELOK AYER|FORT CANNING|BENCOOLEN|JALAN BESAR|BENDEMEER|GEYLANG BAHRU|MATTAR|UBI|KAKI BUKIT|BEDOK NORTH|BEDOK RESERVOIR|TAMPINES WEST|TAMPINES EAST|UPPER CHANGI|EXPO)/)) return "#00539b"; // DTL Blue
  if (name.match(/(WOODLANDS NORTH|WOODLANDS SOUTH|SPRINGLEAF|LENTOR|MAYFLOWER|BRIGHT HILL|UPPER THOMSON|NAPIER|ORCHARD BOULEVARD|GREAT WORLD|HAVELOCK|MAXWELL|SHENTON WAY|MARINA SOUTH|GARDENS BY THE BAY)/)) return "#764c24"; // TEL Brown
  if (name.match(/(LRT)/)) return "#7c878e"; // LRT Grey
  
  return "#2563eb"; // Default Blue
}
