import { MAX_LEASE_DURATION, MAX_SEARCH_QUERY_LENGTH, getCurrentYear } from "../../src/lib/constants";
import { canonicalFlatType } from "../../shared/filter-options";

export const SEARCH_RESULT_LIMIT = 2000;
export const SEARCH_PREDICATE_OWNERSHIP = {
  server: ["town", "flatType", "budgetRange", "flatModel", "floorAreaRange", "mrtMaxDistance", "remainingLeaseMin", "transactionWindow"],
  client: ["textGeographicSearch", "affordability"],
} as const;
export type SearchRequest = { town:string; flatType:string; flatModel:string; budgetMin:number|null; budgetMax:number|null; areaMin:number|null; areaMax:number|null; mrtMax:number|null; remainingLeaseMin:number|null; startMonth:string|null; endMonth:string|null };
export type SearchQueryPlan = { whereSql:string; bindings:unknown[] };
const monthRe=/^\d{4}-(0[1-9]|1[0-2])$/;
const safeParam=(v:string|null)=>v===null?null:(v.length>MAX_SEARCH_QUERY_LENGTH?null:v);
const parseFinite=(v:string|null)=>{ if(!v) return null; const n=Number(v); return Number.isFinite(n)?n:null; };
export function parseSearchRequest(url: URL): SearchRequest { const p=url.searchParams; const req={ town:safeParam(p.get("town"))??"", flatType:safeParam(p.get("flatType"))??"", flatModel:safeParam(p.get("flatModel"))??"", budgetMin:parseFinite(p.get("budgetMin")), budgetMax:parseFinite(p.get("budgetMax")), areaMin:parseFinite(p.get("areaMin")), areaMax:parseFinite(p.get("areaMax")), mrtMax:parseFinite(p.get("mrtMax")), remainingLeaseMin:parseFinite(p.get("remainingLeaseMin")), startMonth:safeParam(p.get("startMonth")), endMonth:safeParam(p.get("endMonth"))}; if(req.budgetMin!==null&&req.budgetMax!==null&&req.budgetMin>req.budgetMax)[req.budgetMin,req.budgetMax]=[req.budgetMax,req.budgetMin]; if(req.areaMin!==null&&req.areaMax!==null&&req.areaMin>req.areaMax)[req.areaMin,req.areaMax]=[req.areaMax,req.areaMin]; if(req.startMonth&&req.endMonth&&req.startMonth>req.endMonth)[req.startMonth,req.endMonth]=[req.endMonth,req.startMonth]; return req; }
export function validateSearchRequest(r:SearchRequest):string|null { if(r.budgetMin!==null&&r.budgetMin<0) return "invalid budgetMin"; if(r.budgetMax!==null&&r.budgetMax<0) return "invalid budgetMax"; if(r.areaMin!==null&&r.areaMin<0) return "invalid areaMin"; if(r.areaMax!==null&&r.areaMax<0) return "invalid areaMax"; if(r.mrtMax!==null&&(r.mrtMax<0||r.mrtMax>20000)) return "invalid mrtMax"; if(r.remainingLeaseMin!==null&&(r.remainingLeaseMin<0||r.remainingLeaseMin>MAX_LEASE_DURATION)) return "invalid remainingLeaseMin"; if(r.startMonth&&!monthRe.test(r.startMonth)) return "invalid startMonth"; if(r.endMonth&&!monthRe.test(r.endMonth)) return "invalid endMonth"; return null; }
export function buildSearchQuery(r:SearchRequest):SearchQueryPlan { const where:string[]=[]; const b:unknown[]=[]; if(r.town){where.push("town = ?");b.push(r.town);} if(r.flatType){const c=canonicalFlatType(r.flatType); where.push("EXISTS (SELECT 1 FROM json_each(blocks.flat_types_json) WHERE UPPER(TRIM(json_each.value)) = ?)"); b.push(c); const path=`$.${JSON.stringify(c)}`; if(r.budgetMin!==null){where.push("COALESCE(CAST(json_extract(blocks.median_price_by_flat_type_json, ?) AS INTEGER), blocks.median_price) >= ?"); b.push(path, r.budgetMin);} if(r.budgetMax!==null){where.push("COALESCE(CAST(json_extract(blocks.median_price_by_flat_type_json, ?) AS INTEGER), blocks.median_price) <= ?"); b.push(path, r.budgetMax);} } else { if(r.budgetMin!==null){where.push("median_price >= ?");b.push(r.budgetMin);} if(r.budgetMax!==null){where.push("median_price <= ?");b.push(r.budgetMax);} } if(r.flatModel){where.push("EXISTS (SELECT 1 FROM json_each(blocks.flat_models_json) WHERE json_each.value = ?)"); b.push(r.flatModel);} if(r.areaMin!==null){where.push("floor_area_max >= ?");b.push(r.areaMin);} if(r.areaMax!==null){where.push("floor_area_min <= ?");b.push(r.areaMax);} if(r.mrtMax!==null){where.push("nearest_mrt_json IS NOT NULL"); where.push("CAST(json_extract(nearest_mrt_json, '$.distanceMeters') AS REAL) <= ?"); b.push(r.mrtMax);} if(r.remainingLeaseMin!==null){where.push("(? - lease_commence_year) <= ?"); b.push(getCurrentYear(), MAX_LEASE_DURATION-r.remainingLeaseMin);} if(r.startMonth){where.push("available_max_month >= ?");b.push(r.startMonth);} if(r.endMonth){where.push("available_min_month <= ?");b.push(r.endMonth);} return { whereSql: where.length?`WHERE ${where.join(" AND ")}`:"", bindings:b }; }
